-- Eski category constraint ni o'chirish
ALTER TABLE products DROP CONSTRAINT IF EXISTS products_category_type_check;
ALTER TABLE shops DROP CONSTRAINT IF EXISTS shops_category_type_check;
ALTER TABLE discounts DROP CONSTRAINT IF EXISTS discounts_category_type_check;

-- Yangi kategoriyalar bilan constraint qo'shish
ALTER TABLE products ADD CONSTRAINT products_category_type_check
CHECK (category_type IN (
  'KIYIM_KECHAK','AYOLLAR_KIYIM','ERKAKLAR_KIYIM','BOLALAR_KIYIM',
  'SPORT_KIYIM','POYABZAL','SUMKA_AKSESSUAR',
  'OZIQ_OVQAT','MEVA_SABZAVOT','GOʻSHT_BALIQ','NON_KONDITYER',
  'SUT_MAHSULOTLARI','ICHIMLIKLAR',
  'PARFYUMERIYA','KOSMETIKA','KIMYO_GIGIYENA',
  'ELEKTRONIKA','TELEFON_AKSESSUAR','MAISHIY_TEXNIKA','KOMPYUTER',
  'QURILISH_MATERIALLARI','MEBEL','UY_JIHOZLARI','GULDASTA_OʻSIMLIK','ELEKTR_JIHOZLARI',
  'AVTOMOBIL','VELOSIPED_SKUTER',
  'TIBBIYOT','OPTIKA','SPORT_ANJOM',
  'BOLALAR','OʻYINCHOQ',
  'QISHLOQ_XOJALIGI','KITOB_QIRTASIYA','ZEV_ZARGARLIK','HAYVONLAR','BOSHQA'
));

ALTER TABLE shops ADD CONSTRAINT shops_category_type_check
CHECK (category_type IN (
  'KIYIM_KECHAK','AYOLLAR_KIYIM','ERKAKLAR_KIYIM','BOLALAR_KIYIM',
  'SPORT_KIYIM','POYABZAL','SUMKA_AKSESSUAR',
  'OZIQ_OVQAT','MEVA_SABZAVOT','GOʻSHT_BALIQ','NON_KONDITYER',
  'SUT_MAHSULOTLARI','ICHIMLIKLAR',
  'PARFYUMERIYA','KOSMETIKA','KIMYO_GIGIYENA',
  'ELEKTRONIKA','TELEFON_AKSESSUAR','MAISHIY_TEXNIKA','KOMPYUTER',
  'QURILISH_MATERIALLARI','MEBEL','UY_JIHOZLARI','GULDASTA_OʻSIMLIK','ELEKTR_JIHOZLARI',
  'AVTOMOBIL','VELOSIPED_SKUTER',
  'TIBBIYOT','OPTIKA','SPORT_ANJOM',
  'BOLALAR','OʻYINCHOQ',
  'QISHLOQ_XOJALIGI','KITOB_QIRTASIYA','ZEV_ZARGARLIK','HAYVONLAR','BOSHQA'
));
